title: "Template"
subtitle: ""
creator: "A. N. Author" # E.g. the author
contributor: "" # E.g. other contributors
subject: "Fiction" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (https://ns.editeur.org/bic_categories)
description: "The Electric Book's blank template." # E.g. the blurb
publisher: "EBW" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2015-12-31" # YYYY-MM-DD e.g. publication date
modified: "2016-06-09" # YYYY-MM-DD e.g. date of last revision
type: "Novel" # e.g. Novel, Poetry, Memoir
identifier: "" # e.g. ISBN or UUID
source: "" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "" # who owns the copyright?
rights: "All rights reserved. No part of this book may be reproduced or transmitted in any form or by any electronic or mechanical means, including photocopying and recording, or any other information storage or retrieval system, without written permission from the publisher." # e.g. a copyright statement
image: "cover.jpg"

products: # Metadata for each product for this title (only use values that override parent metadata)
  print-pdf:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication or creation date
    format: "Print" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-1-titlepage"
      - "0-2-copyright"
      - "0-3-contents"
      - "01"
      - "02"
    toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - label: "Chapter 1"
        file: "01"
        id: "1-hello-world"
      - label: "Chapter 2"
        file: "02"
        id: "2-goodbye-world"
        children:
          - label: "Subsection"
            file: "02"
            id: "example-id"
  web:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital online" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "index"
      - "0-1-titlepage"
      - "0-2-copyright"
      - "0-3-contents"
      - "01": "Chapter One"
      - "02": "Chapter Two"
    nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - label: "Frontmatter"
        children:
          - label: "Cover"
            file: "index"
          - label: "Title page"
            file: "0-1-titlepage"
          - label: "Copyright"
            file: "0-2-copyright"
      - label: "Contents"
        file: "0-3-contents"
      - label: "Chapter One"
        file: "01"
        id: "1-hello-world"
      - label: "Chapter Two"
        file: "02"
        id: "2-goodbye-world"
        children:
          - label: "Subsection"
            file: "02"
            id: "example-id"
    start-page: "0-3-contents" # At which file should users start reading?
    contents-page: "0-3-contents" # Your contents-page file, if you have one.
  epub:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "9780000000000" # e.g. ISBN or UUID
    image: "cover.jpg"
    start-page: "0-3-contents"
    contents-page: "0-3-contents"
    files: # add a value to any file to set any of the guide types listed in http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6
      - "0-0-cover": "cover"
      - "0-1-titlepage": "title-page"
      - "0-2-copyright": "copyright-page"
      - "0-3-contents": "toc"
      - "01": "text"
      - "02"
    toc: # For each menu item, include at least label and file (epub requires file). Optionally add id (for deep linking) and children.
      - label: "Cover"
        file: "0-0-cover"
      - label: "Title page"
        file: "0-1-titlepage"
      - label: "Copyright"
        file: "0-2-copyright"
      - label: "Contents"
        file: "0-3-contents"
      - label: "Chapter One"
        file: "01"
      - label: "Chapter Two"
        file: "02"
  screen-pdf:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-0-cover"
      - "0-1-titlepage"
      - "0-2-copyright"
      - "0-3-contents"
      - "01"
      - "02"
  app:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "index"
      - "0-1-titlepage"
      - "0-2-copyright"
      - "0-3-contents"
      - "01": "Chapter One"
      - "02": "Chapter Two"
    nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - label: "Frontmatter"
        children:
          - label: "Cover"
            file: "index"
          - label: "Title page"
            file: "0-1-titlepage"
          - label: "Copyright"
            file: "0-2-copyright"
      - label: "Contents"
        file: "0-3-contents"
      - label: "Chapter One"
        file: "01"
        id: "1-hello-world"
      - label: "Chapter Two"
        file: "02"
        id: "2-goodbye-world"
        children:
          - label: "Subsection"
            file: "02"
            id: "example-id"
    start-page: "0-3-contents" # At which file should users start reading?
    contents-page: "0-3-contents" # Your contents-page file, if you have one.
